# Form implementation generated from reading ui file 'C:\Users\Juanj\OneDrive\Escritorio\Programación\Corte 3\2 AdmonFacultad\Diseno\DPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 420)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BTerminar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BTerminar.setGeometry(QtCore.QRect(698, 350, 291, 42))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(18)
        self.BTerminar.setFont(font)
        self.BTerminar.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.BTerminar.setObjectName("BTerminar")
        self.LTitulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.LTitulo.setGeometry(QtCore.QRect(20, 30, 891, 33))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(24)
        self.LTitulo.setFont(font)
        self.LTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LTitulo.setObjectName("LTitulo")
        self.BFuente = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BFuente.setGeometry(QtCore.QRect(30, 100, 341, 42))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(18)
        self.BFuente.setFont(font)
        self.BFuente.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);")
        self.BFuente.setObjectName("BFuente")
        self.BProyecto = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BProyecto.setGeometry(QtCore.QRect(30, 170, 341, 42))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(18)
        self.BProyecto.setFont(font)
        self.BProyecto.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 127);")
        self.BProyecto.setObjectName("BProyecto")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Proyectos de Facultad"))
        self.BTerminar.setText(_translate("MainWindow", "Terminar"))
        self.LTitulo.setText(_translate("MainWindow", "ADMINISTRACIÓN PROYECTOS FACULTAD"))
        self.BFuente.setText(_translate("MainWindow", "Fuente"))
        self.BProyecto.setText(_translate("MainWindow", "Proyectos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
